version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::758048059345:user/aws-sam-cli-managed-prod-pipeline-res-PipelineUser-1LZ4F5MLTEDYN"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::758048059345:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-103IPXFIDM2JI"
cloudformation_execution_role = "arn:aws:iam::758048059345:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-IQIKGAGPON19"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-n2ywhnpipxzm"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::758048059345:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1IBJIEYDHGQSK"
cloudformation_execution_role = "arn:aws:iam::758048059345:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-K044U7CB5XA3"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-hbfa7wcf31xk"
image_repository = ""
region = "us-east-1"
